import { useState, useRef } from "react";
import {
  UploadCloud,
  FileText,
  Sparkles,
  Check,
  AlertTriangle,
  Calendar,
  MapPin,
  Clock,
  User,
  Layers,
  ArrowRight,
  Plus,
  Trash2,
  X,
} from "lucide-react";
import { Modal, Input, Badge } from "./ui";
import Button from "./ui/Button";
import { parseEventDocumentWithAI } from "../services/gemini";
import { addTasksBatchToEvent } from "../hooks/useTasks";
import { setSessionsBatchForEvent } from "../hooks/useSessions";
import { useNotifications } from "../hooks/useNotifications";
import {
  getStoredEvents,
  saveStoredEvents,
  getActiveUserEmail,
} from "../lib/storage";

export default function UploadDocumentModal({ open, onClose, onEventCreated }) {
  const { addNotification } = useNotifications();
  const fileInputRef = useRef(null);

  const [activeTab, setActiveTab] = useState("file"); // "file" or "paste"
  const [file, setFile] = useState(null);
  const [pastedText, setPastedText] = useState("");
  const [isDragging, setIsDragging] = useState(false);

  const [parsing, setParsing] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");

  // Parsed AI result
  const [parsedData, setParsedData] = useState(null); // { event, sessions, tasks, missingDetails }

  // Editable fields for missing details or adjustments
  const [eventForm, setEventForm] = useState({
    name: "",
    category: "Flagship Hackathon",
    tagline: "",
    date: "",
    location: "",
  });

  const [committing, setCommitting] = useState(false);

  const resetState = () => {
    setFile(null);
    setPastedText("");
    setParsedData(null);
    setErrorMsg("");
    setParsing(false);
    setCommitting(false);
  };

  const handleClose = () => {
    resetState();
    onClose();
  };

  const handleFileSelect = (selectedFile) => {
    if (!selectedFile) return;
    setFile(selectedFile);
    setErrorMsg("");
  };

  const readTextFromFile = (fileObj) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e) => resolve(e.target.result);
      reader.onerror = () => reject(new Error("Failed to read file contents"));
      reader.readAsText(fileObj);
    });
  };

  const handleAnalyze = async () => {
    let rawText = "";

    if (activeTab === "file") {
      if (!file) {
        setErrorMsg("Please select or drop an event document file first.");
        return;
      }
      try {
        rawText = await readTextFromFile(file);
      } catch (err) {
        setErrorMsg("Could not read file text. Please try pasting the text directly.");
        return;
      }
    } else {
      if (!pastedText.trim()) {
        setErrorMsg("Please paste your event schedule, agenda, or brief.");
        return;
      }
      rawText = pastedText.trim();
    }

    setParsing(true);
    setErrorMsg("");

    try {
      const result = await parseEventDocumentWithAI(rawText);
      setParsedData(result);
      setEventForm({
        name: result.event.name || "AI Generated Event",
        category: result.event.category || "Flagship Hackathon",
        tagline: result.event.tagline || "",
        date: result.event.date || new Date().toISOString().split("T")[0],
        location: result.event.location || "Campus Venue",
      });
    } catch (err) {
      console.error("Document parsing error:", err);
      setErrorMsg(`Failed to parse document: ${err.message}`);
    } finally {
      setParsing(false);
    }
  };

  const handleCommitEvent = async () => {
    if (!eventForm.name.trim()) {
      setErrorMsg("Event name is required.");
      return;
    }
    if (!eventForm.date) {
      setErrorMsg("Event date is required.");
      return;
    }

    setCommitting(true);
    setErrorMsg("");

    try {
      const newEventId =
        eventForm.name
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/^-|-$/g, "") +
        "-" +
        Date.now().toString().slice(-4);

      const newEvent = {
        id: newEventId,
        ownerEmail: getActiveUserEmail(),
        name: eventForm.name.trim(),
        category: eventForm.category || "Flagship Hackathon",
        tagline: eventForm.tagline.trim() || "Generated by AI Document Parser",
        date: eventForm.date,
        location: eventForm.location.trim() || "Main Venue",
        status: "planning",
        color: "accent",
      };

      // 1. Save event to user-scoped event list
      const currentEvents = getStoredEvents();
      const updatedEvents = [newEvent, ...currentEvents];
      saveStoredEvents(updatedEvents);

      // 2. Commit parsed sessions
      if (parsedData?.sessions?.length > 0) {
        await setSessionsBatchForEvent(newEventId, parsedData.sessions);
      }

      // 3. Commit parsed tasks
      if (parsedData?.tasks?.length > 0) {
        await addTasksBatchToEvent(newEventId, parsedData.tasks);
      }

      addNotification({
        type: "ai",
        message: `Created event "${newEvent.name}" with ${parsedData?.sessions?.length || 0} sessions and ${parsedData?.tasks?.length || 0} tasks from uploaded document!`,
      });

      if (typeof window !== "undefined") {
        window.dispatchEvent(new CustomEvent("clubops-data-updated"));
      }

      onEventCreated?.(newEvent);
      handleClose();
    } catch (err) {
      console.error("Failed to commit event and sessions:", err);
      setErrorMsg(`Error creating event: ${err.message}`);
    } finally {
      setCommitting(false);
    }
  };

  return (
    <Modal open={open} onClose={handleClose} title="Upload Event Document (AI Auto-Create)">
      <div className="space-y-4">
        {!parsedData ? (
          <>
            <p className="text-xs font-bold text-neo-ink/70">
              Upload an event flyer, brief, schedule document, or run-of-show. ChronOps will extract the event metadata, build the live stage session timeline, and assign volunteer tasks automatically.
            </p>

            {/* Tabs */}
            <div className="flex border-b-4 border-neo-ink bg-neo-white">
              <button
                type="button"
                onClick={() => setActiveTab("file")}
                className={[
                  "flex-1 py-2 font-black text-xs uppercase tracking-wider cursor-pointer border-r-4 border-neo-ink",
                  activeTab === "file" ? "bg-neo-secondary text-neo-ink" : "text-neo-ink/60 hover:text-neo-ink",
                ].join(" ")}
              >
                Upload File (.txt, .md, .pdf, .json)
              </button>
              <button
                type="button"
                onClick={() => setActiveTab("paste")}
                className={[
                  "flex-1 py-2 font-black text-xs uppercase tracking-wider cursor-pointer",
                  activeTab === "paste" ? "bg-neo-secondary text-neo-ink" : "text-neo-ink/60 hover:text-neo-ink",
                ].join(" ")}
              >
                Paste Document Text
              </button>
            </div>

            {activeTab === "file" ? (
              <div
                onDragOver={(e) => {
                  e.preventDefault();
                  setIsDragging(true);
                }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={(e) => {
                  e.preventDefault();
                  setIsDragging(false);
                  if (e.dataTransfer.files?.[0]) {
                    handleFileSelect(e.dataTransfer.files[0]);
                  }
                }}
                onClick={() => fileInputRef.current?.click()}
                className={[
                  "border-4 border-dashed p-8 text-center cursor-pointer transition-all duration-100",
                  isDragging
                    ? "border-neo-accent bg-neo-accent/10"
                    : file
                    ? "border-neo-ink bg-neo-secondary/20"
                    : "border-neo-ink/40 hover:border-neo-ink bg-neo-white",
                ].join(" ")}
              >
                <input
                  type="file"
                  ref={fileInputRef}
                  onChange={(e) => handleFileSelect(e.target.files?.[0])}
                  className="hidden"
                  accept=".txt,.md,.json,.csv,.pdf,.doc,.docx"
                />
                <UploadCloud size={36} strokeWidth={2.5} className="mx-auto mb-2 text-neo-ink/60" />
                {file ? (
                  <div>
                    <p className="font-black text-sm text-neo-ink uppercase">{file.name}</p>
                    <p className="text-[11px] font-bold text-neo-ink/60">
                      {(file.size / 1024).toFixed(1)} KB • Click to choose a different file
                    </p>
                  </div>
                ) : (
                  <div>
                    <p className="font-bold text-xs uppercase tracking-wider text-neo-ink">
                      Drag & Drop your Event Document or Click to Browse
                    </p>
                    <p className="text-[10px] font-bold text-neo-ink/50 mt-1 uppercase">
                      Supports: .txt, .md, .pdf, .json, .csv, and brochures
                    </p>
                  </div>
                )}
              </div>
            ) : (
              <div>
                <textarea
                  rows={6}
                  placeholder="Paste your event brief, agenda schedule, session timings, and organizer action items here..."
                  value={pastedText}
                  onChange={(e) => setPastedText(e.target.value)}
                  className="w-full p-3 font-mono text-xs border-4 border-neo-ink bg-neo-white focus:outline-none focus:bg-neo-secondary focus:shadow-neo-sm"
                />
              </div>
            )}

            {errorMsg && (
              <div className="bg-neo-accent/10 border-4 border-neo-accent p-3">
                <p className="font-bold text-xs text-neo-accent">{errorMsg}</p>
              </div>
            )}

            <div className="flex justify-end gap-2 pt-2 border-t-2 border-neo-ink/20">
              <Button type="button" variant="outline" size="sm" onClick={handleClose}>
                Cancel
              </Button>
              <Button
                type="button"
                variant="primary"
                size="sm"
                disabled={parsing}
                onClick={handleAnalyze}
              >
                <Sparkles size={16} strokeWidth={3} />
                {parsing ? "Parsing Document with AI..." : "Analyze & Generate Event"}
              </Button>
            </div>
          </>
        ) : (
          /* Parsed Results & Missing Details Confirmation View */
          <div className="space-y-4 max-h-[75vh] overflow-y-auto pr-1">
            {/* Missing Details Alert Banner */}
            {parsedData.missingDetails && parsedData.missingDetails.length > 0 && (
              <div className="bg-neo-secondary/40 border-4 border-neo-ink p-3 shadow-neo-sm">
                <div className="flex items-center gap-1.5 font-black text-xs uppercase tracking-wider text-neo-ink mb-1">
                  <AlertTriangle size={16} strokeWidth={3} className="text-neo-ink" />
                  Missing Details Detected in Document
                </div>
                <p className="text-[11px] font-bold text-neo-ink/80 mb-2">
                  The uploaded document did not include the following details. You can specify or confirm them below:
                </p>
                <ul className="list-disc list-inside space-y-0.5 text-[11px] font-bold text-neo-ink/90">
                  {parsedData.missingDetails.map((msg, i) => (
                    <li key={i}>{msg}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Event Metadata Card */}
            <div className="border-4 border-neo-ink bg-neo-white p-3 shadow-neo-sm space-y-3">
              <div className="flex items-center justify-between border-b-2 border-neo-ink/20 pb-2">
                <span className="font-black text-xs uppercase tracking-wider text-neo-ink flex items-center gap-1">
                  <Layers size={14} strokeWidth={3} />
                  Event Information
                </span>
                <Badge color="accent">AI Extracted</Badge>
              </div>

              <div>
                <label className="block font-bold text-[11px] uppercase tracking-wider mb-0.5">
                  Event Name *
                </label>
                <Input
                  value={eventForm.name}
                  onChange={(e) => setEventForm((prev) => ({ ...prev, name: e.target.value }))}
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <div>
                  <label className="block font-bold text-[11px] uppercase tracking-wider mb-0.5">
                    Date *
                  </label>
                  <Input
                    type="date"
                    value={eventForm.date}
                    onChange={(e) => setEventForm((prev) => ({ ...prev, date: e.target.value }))}
                  />
                </div>
                <div>
                  <label className="block font-bold text-[11px] uppercase tracking-wider mb-0.5">
                    Venue / Location *
                  </label>
                  <Input
                    placeholder="e.g. Main Auditorium"
                    value={eventForm.location}
                    onChange={(e) => setEventForm((prev) => ({ ...prev, location: e.target.value }))}
                  />
                </div>
              </div>
            </div>

            {/* Extracted Sessions Preview */}
            <div className="border-4 border-neo-ink bg-neo-white p-3 shadow-neo-sm space-y-2">
              <div className="flex items-center justify-between border-b-2 border-neo-ink/20 pb-1.5">
                <span className="font-black text-xs uppercase tracking-wider text-neo-ink flex items-center gap-1">
                  <Clock size={14} strokeWidth={3} />
                  Extracted Sessions ({parsedData.sessions?.length || 0})
                </span>
                <span className="text-[10px] font-bold text-neo-ink/60 uppercase">
                  Run of Show Timeline
                </span>
              </div>
              <div className="border-2 border-neo-ink bg-neo-white max-h-40 overflow-y-auto divide-y divide-neo-ink/15">
                {parsedData.sessions?.map((s, idx) => (
                  <div
                    key={idx}
                    className="flex items-center justify-between p-2 hover:bg-neo-bg/30 transition-colors text-xs"
                  >
                    <div className="flex items-center gap-2">
                      <span className="font-black font-mono text-[11px] bg-neo-secondary px-1.5 py-0.5 border border-neo-ink">
                        {s.startTime}
                      </span>
                      <div>
                        <p className="font-bold text-xs text-neo-ink line-clamp-1">{s.title}</p>
                        {s.speaker && (
                          <p className="text-[10px] font-bold text-neo-ink/60 uppercase">
                            {s.speaker}
                          </p>
                        )}
                      </div>
                    </div>
                    <Badge color={s.sessionType === "fixed" ? "secondary" : "muted"} className="!text-[9px]">
                      {s.durationMinutes}m • {s.sessionType}
                    </Badge>
                  </div>
                ))}
              </div>
            </div>

            {/* Extracted Tasks Preview */}
            <div className="border-4 border-neo-ink bg-neo-white p-3 shadow-neo-sm space-y-2">
              <div className="flex items-center justify-between border-b-2 border-neo-ink/20 pb-1.5">
                <span className="font-black text-xs uppercase tracking-wider text-neo-ink flex items-center gap-1">
                  <Check size={14} strokeWidth={3} />
                  Extracted Operational Tasks ({parsedData.tasks?.length || 0})
                </span>
                <span className="text-[10px] font-bold text-neo-ink/60 uppercase">
                  Kanban Backlog
                </span>
              </div>
              <div className="border-2 border-neo-ink bg-neo-white max-h-40 overflow-y-auto divide-y divide-neo-ink/15">
                {parsedData.tasks?.map((t, idx) => (
                  <div
                    key={idx}
                    className="flex items-center justify-between p-2 hover:bg-neo-bg/30 transition-colors text-xs"
                  >
                    <div className="flex items-center gap-1.5">
                      <Badge color={t.priority === "high" ? "accent" : "secondary"} className="!text-[9px]">
                        {t.priority}
                      </Badge>
                      <p className="font-bold text-xs text-neo-ink line-clamp-1">{t.title}</p>
                    </div>
                    {t.assignee && (
                      <span className="text-[10px] font-bold text-neo-ink/60 uppercase">
                        {t.assignee}
                      </span>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {errorMsg && (
              <div className="bg-neo-accent/10 border-4 border-neo-accent p-3">
                <p className="font-bold text-xs text-neo-accent">{errorMsg}</p>
              </div>
            )}

            {/* Commit / Cancel Actions */}
            <div className="flex justify-end gap-2 pt-3 border-t-2 border-neo-ink/20">
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={committing}
                onClick={() => setParsedData(null)}
              >
                Back to Upload
              </Button>
              <Button
                type="button"
                variant="primary"
                size="sm"
                disabled={committing}
                onClick={handleCommitEvent}
              >
                <Check size={16} strokeWidth={3} />
                {committing ? "Building Event & Boards..." : "Confirm & Create Event Board"}
              </Button>
            </div>
          </div>
        )}
      </div>
    </Modal>
  );
}
